# Generated by Django 3.0 on 2020-12-27 23:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201226_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 12, 28)),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_details', models.TextField(max_length=4000)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('mark_as_read', models.BooleanField(default=False)),
                ('mark_as_solved', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Feedback', 'Help'), ('Feedback', 'Feedback'), ('Report', 'Report')], max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')])),
                ('feedback_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
