# Generated by Django 3.0 on 2020-12-28 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201228_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rate_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
