# Generated by Django 3.0 on 2020-12-28 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='person',
        ),
        migrations.AddField(
            model_name='achievements',
            name='holder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='holder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')]),
        ),
    ]
