# Generated by Django 3.0 on 2021-01-04 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201228_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
    ]
