# Generated by Django 3.0 on 2021-01-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210104_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProfessional',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('info', models.TextField(max_length=10000)),
            ],
        ),
    ]
