# Generated by Django 3.0 on 2021-01-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_aboutprofessional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutprofessional',
            name='info',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
