# Generated by Django 3.0 on 2020-12-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentschedule',
            old_name='user',
            new_name='creator',
        ),
    ]
