# Generated by Django 3.0 on 2020-12-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_appointments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='day',
            new_name='date',
        ),
    ]
